### ISSUE TITLE
Custom commands execution

### ISSUE THREAD

**Issue by oljekechoro** [semrel-extra/zx-bulk-release#5]
## Issue type
* [ ] bug report
* [x] idea
* [ ] question
* [ ] other

## Expected behavior
User can add a template string with commands to execute after all release stuff is done. The template string accepts vars from release context.

## Actual behavior
There is no such option.

Your case may be a known design limitation. -->
* [x] I've read the docs. This case is not mentioned
* [x] Similar issue does not exist

**Comment by antongolub** [comment]
```js
{
   publishCmd: 'echo "custom publish: ${{name}} ${{version}}"'
}
```
